language: node_js
node_js:
  - 0.10

before_install:
  - gem update --system
  - gem install sass

notifications:
  email: false

branches:
  only:
    - development

cache:
  directories:
    - node_modules